"""
Django settings for djangoproj project.

Generated by 'django-admin startproject' using Django 3.2.5.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    'django-insecure-ccow$tz_=9%dxu4(0%^(z%nx32#s@(zt9$ih@)5l54yny)wm-0'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 1. Hostnames only (no http:// or https:// protocol prefixes)
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    (
        'larrysonbiya-8000.theianext-0-labs-prod-misc-tools-us-east-0'
        '.proxy.cognitiveclass.ai'
    ),
    '*',
]

# 2. Complete origins including scheme (https:// or http://)
CSRF_TRUSTED_ORIGINS = [
    (
        'https://larrysonbiya-8000.theiadockernext-1-labs-prod-theiak8s-4'
        '-tor01.proxy.cognitiveclass.ai'
    ),
    (
        'http://larrysonbiya-8000.theiadockernext-1-labs-prod-theiak8s-4'
        '-tor01.proxy.cognitiveclass.ai'
    ),
]

AUTH_PASSWORD_VALIDATORS = [
    {

        'NAME': (
            'django.contrib.auth.password_validation'
            '.UserAttributeSimilarityValidator'
        )
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.MinimumLengthValidator'
        )
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.CommonPasswordValidator'
        )
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.NumericPasswordValidator'
        )
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(STATIC_ROOT, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/static'),
    os.path.join(BASE_DIR, 'frontend/build'),
    os.path.join(BASE_DIR, 'frontend/build/static'),
]
